version: '3'

services:
  kniffel-ks-backend:
    image: reactivePlusConfigSource
    container_name: reactivePlusConfigSource
    networks:
      - my-network
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=service-database-mysql
      - DATABASE_PORT=3306
    volumes:
      - /pathToMySharedVolume/:/sharedVolume/

networks:
  my-network:
    external:
      name: my-network

